### ISSUE TITLE
Jaba URL decoding

### ISSUE THREAD

**Issue by kisileno** [kelebra/tkachuko-blog#51]
https://github.com/kelebra/tkachuko-blog/blob/master/backend/src/main/scala/com/tkachuko/blog/backend/rest/RestService.scala#L53

```Jaba
String result = java.net.URLDecoder.decode(url, "UTF-8");
```

**Comment by kelebra** [comment]
LGTM catch 👍 New version will be deployed today with the fix

**Comment by kisileno** [comment]
🍻

**Comment by kelebra** [comment]
Done in PR #52
